sudo: false
language: php

php:
  - 5.4

  env:

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

matrix:
  fast_finish: true
